// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './AaveV3.sol';
import {ICollector} from './common/ICollector.sol';

library AaveV3Sepolia {
  // https://sepolia.etherscan.io/address/0x4B3Ddc79b72c13Ca3FcE86cfC433db15999c4A38
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x4B3Ddc79b72c13Ca3FcE86cfC433db15999c4A38);

  // https://sepolia.etherscan.io/address/0xE409F105ec31C66E0b5a5A517779e36f25826C73
  IPool internal constant POOL = IPool(0xE409F105ec31C66E0b5a5A517779e36f25826C73);

  // https://sepolia.etherscan.io/address/0xc1EA8b8b7a5445C94D85baD135C870a3aB217205
  address internal constant POOL_IMPL = 0xc1EA8b8b7a5445C94D85baD135C870a3aB217205;

  // https://sepolia.etherscan.io/address/0xE9640A7d4E05ebfE1b301cC0d4d78b7FEf049D32
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0xE9640A7d4E05ebfE1b301cC0d4d78b7FEf049D32);

  // https://sepolia.etherscan.io/address/0x228eaCC035fC9817f95B6e0Da1b96E115B04F7Cc
  address internal constant POOL_CONFIGURATOR_IMPL = 0x228eaCC035fC9817f95B6e0Da1b96E115B04F7Cc;

  // https://sepolia.etherscan.io/address/0x8F9a3d097B537bD5b595506Cf1e95215028d27F4
  IAaveOracle internal constant ORACLE = IAaveOracle(0x8F9a3d097B537bD5b595506Cf1e95215028d27F4);

  // https://sepolia.etherscan.io/address/0x93C9050db40120c355c8F1849c5bb1d6b6559edd
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x93C9050db40120c355c8F1849c5bb1d6b6559edd);

  // https://sepolia.etherscan.io/address/0xD2Dd72BBa77bD7b0B0A0af3454b90E39729fB894
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0xD2Dd72BBa77bD7b0B0A0af3454b90E39729fB894);

  // https://sepolia.etherscan.io/address/0x1716C4d49E9D81c17608CD9a45b1023ac9DF6c73
  address internal constant ACL_ADMIN = 0x1716C4d49E9D81c17608CD9a45b1023ac9DF6c73;

  // https://sepolia.etherscan.io/address/0x44161818C4DEb6aF862637092AC19C8f41aBA1fD
  ICollector internal constant COLLECTOR = ICollector(0x44161818C4DEb6aF862637092AC19C8f41aBA1fD);

  // https://sepolia.etherscan.io/address/0x515655a8a33ff0542F63A8f99eE7c7886B7951B8
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x515655a8a33ff0542F63A8f99eE7c7886B7951B8;

  // https://sepolia.etherscan.io/address/0x1C6202e43e38b58F4295832928cA9b4267090414
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0x1C6202e43e38b58F4295832928cA9b4267090414;

  // https://sepolia.etherscan.io/address/0x20460F1f13698d2B8297150A16CD004892af01E4
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x20460F1f13698d2B8297150A16CD004892af01E4;

  // https://sepolia.etherscan.io/address/0xad4004E3750b015Fe54682feC08A19b007fbF5bf
  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xad4004E3750b015Fe54682feC08A19b007fbF5bf;

  // https://sepolia.etherscan.io/address/0x99F5200d6329CcB7aD3838A658a7BdFA66f39DE5
  address internal constant EMISSION_MANAGER = 0x99F5200d6329CcB7aD3838A658a7BdFA66f39DE5;

  // https://sepolia.etherscan.io/address/0x5d51873D1A7A49C1a255Be3Be3D138580B2333B9
  address internal constant FAUCET = 0x5d51873D1A7A49C1a255Be3Be3D138580B2333B9;

  // https://sepolia.etherscan.io/address/0x24dF695AD3a3F77836CC33989FF553Edd9e8CA9c
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x24dF695AD3a3F77836CC33989FF553Edd9e8CA9c;

  // https://sepolia.etherscan.io/address/0x2526Ea201c6527111ec8A5880cedc37C343E6694
  address internal constant UI_POOL_DATA_PROVIDER = 0x2526Ea201c6527111ec8A5880cedc37C343E6694;

  // https://sepolia.etherscan.io/address/0x95e89e64105674622963BbeAb629063BAc5EA4Ec
  address internal constant WALLET_BALANCE_PROVIDER = 0x95e89e64105674622963BbeAb629063BAc5EA4Ec;

  // https://sepolia.etherscan.io/address/0x8A294edFB7F1679e393994b36218Bc4ec310Dd82
  address internal constant WETH_GATEWAY = 0x8A294edFB7F1679e393994b36218Bc4ec310Dd82;

  // https://sepolia.etherscan.io/address/0x8Ce0B61E78c313acf4cA0895ba01CF637775f4Dd
  address internal constant STATIC_A_TOKEN_FACTORY = 0x8Ce0B61E78c313acf4cA0895ba01CF637775f4Dd;

  // https://sepolia.etherscan.io/address/0x1bc7faac29EE71C96e5102cc5A094C568362cf10
  address internal constant UI_GHO_DATA_PROVIDER = 0x1bc7faac29EE71C96e5102cc5A094C568362cf10;
}

library AaveV3SepoliaAssets {
  // https://sepolia.etherscan.io/address/0x900fdE742B4C918D1Dc8636846e3704da1c41660
  address internal constant AAVE_UNDERLYING = 0x900fdE742B4C918D1Dc8636846e3704da1c41660;

  uint8 internal constant AAVE_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0x9d881F8c953FB70524b49922852FE4da8E8D05D1
  address internal constant AAVE_A_TOKEN = 0x9d881F8c953FB70524b49922852FE4da8E8D05D1;

  // https://sepolia.etherscan.io/address/0xf012852ebD5De3e32313F1Cf33E3d10924ce162b
  address internal constant AAVE_V_TOKEN = 0xf012852ebD5De3e32313F1Cf33E3d10924ce162b;

  // https://sepolia.etherscan.io/address/0xD786F62395648F584817EdCe73cF77533F6B36E8
  address internal constant AAVE_S_TOKEN = 0xD786F62395648F584817EdCe73cF77533F6B36E8;

  // https://sepolia.etherscan.io/address/0xbb76528d779140d644649C5122Fe933830C808b9
  address internal constant AAVE_ORACLE = 0xbb76528d779140d644649C5122Fe933830C808b9;

  // https://sepolia.etherscan.io/address/0xAD1C87e0CE1bEB1ed692940C491a3577C45C3bA8
  address internal constant AAVE_INTEREST_RATE_STRATEGY =
    0xAD1C87e0CE1bEB1ed692940C491a3577C45C3bA8;

  // https://sepolia.etherscan.io/address/0xE25B473F26dF5002a1a80Cc2c7E7b8575b003f12
  address internal constant DAI_UNDERLYING = 0xE25B473F26dF5002a1a80Cc2c7E7b8575b003f12;

  uint8 internal constant DAI_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0xE45E4a26353A3719f8C34A448BC05660424fb5b4
  address internal constant DAI_A_TOKEN = 0xE45E4a26353A3719f8C34A448BC05660424fb5b4;

  // https://sepolia.etherscan.io/address/0x0B627c8082E1A9B2Ae78dE1f333B1d218281b29C
  address internal constant DAI_V_TOKEN = 0x0B627c8082E1A9B2Ae78dE1f333B1d218281b29C;

  // https://sepolia.etherscan.io/address/0xA7f6fDE9f414C2cd2A35e028B377Ec733A1bA103
  address internal constant DAI_S_TOKEN = 0xA7f6fDE9f414C2cd2A35e028B377Ec733A1bA103;

  // https://sepolia.etherscan.io/address/0xcD6290eB9aEf7C30A48A8282DdEb22Ae8d99d8C7
  address internal constant DAI_ORACLE = 0xcD6290eB9aEf7C30A48A8282DdEb22Ae8d99d8C7;

  // https://sepolia.etherscan.io/address/0xBF9E96481B3f412073742ddE3285CDceaD991dc4
  address internal constant DAI_INTEREST_RATE_STRATEGY = 0xBF9E96481B3f412073742ddE3285CDceaD991dc4;

  // https://sepolia.etherscan.io/address/0x046914F7F73BfC68Dd01b2811CCb9C589Ad1Ea44
  address internal constant USDC_UNDERLYING = 0x046914F7F73BfC68Dd01b2811CCb9C589Ad1Ea44;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://sepolia.etherscan.io/address/0x9A120aA823c1fbF0C852D50b9b0161f15eDc6016
  address internal constant USDC_A_TOKEN = 0x9A120aA823c1fbF0C852D50b9b0161f15eDc6016;

  // https://sepolia.etherscan.io/address/0x7de7fC2b6cA66CE453a1E2C7176FEf516ED45597
  address internal constant USDC_V_TOKEN = 0x7de7fC2b6cA66CE453a1E2C7176FEf516ED45597;

  // https://sepolia.etherscan.io/address/0xD0d4Cf56bF139976138340F073F0506795e70b5d
  address internal constant USDC_S_TOKEN = 0xD0d4Cf56bF139976138340F073F0506795e70b5d;

  // https://sepolia.etherscan.io/address/0xb0CFD94d3d6d4265C25c50F7D1C1DA759e269552
  address internal constant USDC_ORACLE = 0xb0CFD94d3d6d4265C25c50F7D1C1DA759e269552;

  // https://sepolia.etherscan.io/address/0xF1131C7A3F5696bC7530823af7c5c31358e8D14A
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0xF1131C7A3F5696bC7530823af7c5c31358e8D14A;

  // https://sepolia.etherscan.io/address/0xEfDd366Cde8860b3E5f904286B056056939656B9
  address internal constant WETH_UNDERLYING = 0xEfDd366Cde8860b3E5f904286B056056939656B9;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0xe6040131025ECd005181FF218e9F5B3183F8ce81
  address internal constant WETH_A_TOKEN = 0xe6040131025ECd005181FF218e9F5B3183F8ce81;

  // https://sepolia.etherscan.io/address/0xc0e40A697d728383376D45744066FF0131aB6d7e
  address internal constant WETH_V_TOKEN = 0xc0e40A697d728383376D45744066FF0131aB6d7e;

  // https://sepolia.etherscan.io/address/0x28ABfDdb5a1416DD280A42575021B062ADc20128
  address internal constant WETH_S_TOKEN = 0x28ABfDdb5a1416DD280A42575021B062ADc20128;

  // https://sepolia.etherscan.io/address/0xba1C17d40A1C53680545cF78B7c4c9C438161Eba
  address internal constant WETH_ORACLE = 0xba1C17d40A1C53680545cF78B7c4c9C438161Eba;

  // https://sepolia.etherscan.io/address/0xAD1C87e0CE1bEB1ed692940C491a3577C45C3bA8
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0xAD1C87e0CE1bEB1ed692940C491a3577C45C3bA8;

  // https://sepolia.etherscan.io/address/0xA61841924ceE693A36d19E6528d07f6f48aEAeB2
  address internal constant LINK_UNDERLYING = 0xA61841924ceE693A36d19E6528d07f6f48aEAeB2;

  uint8 internal constant LINK_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0x821954DEeAF34ACC7CB00E25c12Da9e6FB9Dc55B
  address internal constant LINK_A_TOKEN = 0x821954DEeAF34ACC7CB00E25c12Da9e6FB9Dc55B;

  // https://sepolia.etherscan.io/address/0x231Be89ca0F7753bB09F16e0e98A532591e417a6
  address internal constant LINK_V_TOKEN = 0x231Be89ca0F7753bB09F16e0e98A532591e417a6;

  // https://sepolia.etherscan.io/address/0xa79aC08Ac445994c0a1eAAe0B8C5227935871e55
  address internal constant LINK_S_TOKEN = 0xa79aC08Ac445994c0a1eAAe0B8C5227935871e55;

  // https://sepolia.etherscan.io/address/0xe24a3f34Ff28E137FfE71C786248C0c9eDF67e53
  address internal constant LINK_ORACLE = 0xe24a3f34Ff28E137FfE71C786248C0c9eDF67e53;

  // https://sepolia.etherscan.io/address/0xAD1C87e0CE1bEB1ed692940C491a3577C45C3bA8
  address internal constant LINK_INTEREST_RATE_STRATEGY =
    0xAD1C87e0CE1bEB1ed692940C491a3577C45C3bA8;

  // https://sepolia.etherscan.io/address/0x9551EEeBB5F1b7F4bA2E50FF10b6BCEbdA187F00
  address internal constant GHO_UNDERLYING = 0x9551EEeBB5F1b7F4bA2E50FF10b6BCEbdA187F00;

  uint8 internal constant GHO_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0x1CF95CdD59b3088305c89F9a74e06E8e2E5A82e7
  address internal constant GHO_A_TOKEN = 0x1CF95CdD59b3088305c89F9a74e06E8e2E5A82e7;

  // https://sepolia.etherscan.io/address/0x03C5B7e73eb51c0059E3Dba0f97EB9BBdE55AC9D
  address internal constant GHO_V_TOKEN = 0x03C5B7e73eb51c0059E3Dba0f97EB9BBdE55AC9D;

  // https://sepolia.etherscan.io/address/0xC70B47F4561D2bb60A273720993Bb14615Cb36CF
  address internal constant GHO_S_TOKEN = 0xC70B47F4561D2bb60A273720993Bb14615Cb36CF;

  // https://sepolia.etherscan.io/address/0xBf5EF5D1884e238E842cb84bfbbaf7Be83aC4F65
  address internal constant GHO_ORACLE = 0xBf5EF5D1884e238E842cb84bfbbaf7Be83aC4F65;

  // https://sepolia.etherscan.io/address/0xb11289C26427245b8AC2827953389b577156f650
  address internal constant GHO_INTEREST_RATE_STRATEGY = 0xb11289C26427245b8AC2827953389b577156f650;
}

library AaveV3SepoliaEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant STABLE_EMODE = 1;
}
