// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library MiscSepolia {
  // https://sepolia.etherscan.io/address/0x4b17b158736574da09697A258573dF9d963079e2
  address internal constant TRANSPARENT_PROXY_FACTORY = 0x4b17b158736574da09697A258573dF9d963079e2;

  // https://sepolia.etherscan.io/address/0xBD586987Ed500154f917Bf6fda191B860C268C98
  address internal constant PROXY_ADMIN = 0xBD586987Ed500154f917Bf6fda191B860C268C98;

  // https://sepolia.etherscan.io/address/0x9551EEeBB5F1b7F4bA2E50FF10b6BCEbdA187F00
  address internal constant GHO_TOKEN = 0x9551EEeBB5F1b7F4bA2E50FF10b6BCEbdA187F00;

  // https://sepolia.etherscan.io/address/0xaFc3BF553B4F6B22fB0d226306B5BDcE60B45aD9
  address internal constant GHO_FLASHMINTER_FACILITATOR =
    0xaFc3BF553B4F6B22fB0d226306B5BDcE60B45aD9;

  // https://sepolia.etherscan.io/address/0x7B92e514C5A5295bEC14f94BDD951c7E32797093
  address internal constant ECOSYSTEM_RESERVE = 0x7B92e514C5A5295bEC14f94BDD951c7E32797093;
}
